# compose 파일 버전
version: '3'
services:
    backend:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            - .:/backend
        command: sh -c "sleep 10 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        restart: on-failure
        ports:
            - 8000:8000
        expose:
            - 8000