name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Python 환경 설정
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. 의존성 설치
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. 데이터베이스 설정 (SQLite 사용 예제)
    #- name: Set up database
    #  run: |
    #    python manage.py migrate

    # 5. 테스트 실행
    - name: Run tests
      run: |
        python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 배포 단계 예제 (AWS나 다른 플랫폼 설정 필요)
    #- name: Deploy to Production
    #  run: |
    #    echo "Deploy script here..."
        # Django 배포에 맞는 스크립트 추가
